actionbar-tekst: "&bTid: &3{time}s" ##{time} er tiden i saferoomet
saferoom:
  tid: 120 ##skal angives i sekunder
  1:
    region-name: "saferoom-1"
    teleport-out: "world;100;63;100;0.0;0.0"
  2:
    region-name: "saferoom-2"
    teleport-out: "world;69.579;63.0000;295.553;0.0;0.0"
  3:
    region-name: "saferoom-3"
    teleport-out: "world;100;63;100;0.0;0.0"
  4:
    region-name: "saferoom-4"
    teleport-out: "world;100;63;100;0.0;0.0"

vagt-groups:
  - "vagt"
  - "officer"
  - "inspektør"
  - "direktør"